### PR TITLE
do not use dot as keydelimeter

### PR DESCRIPTION
**Pull request by nikitindv**

### CODE REVIEW

**Comment by gerbenmeyer** [comment]
What is actually the issue with using a dot as key delimiter?

**Comment by nikitindv** [comment]
We are using natural language statements as message ids, they can contain
dot as end of statement, so fetchtranslation method will fail.


26 дек. 2016 г. 21:45 пользователь "Gerben Meyer" <notifications@github.com>
написал:

**Comment by krpiatkowski** [comment]
+1

**Comment by Laro88** [comment]
We have a limilar solution with some legacy translation content base.

login.login has a text ["Anmelden"], however login.login.details ["Bitten credentials eingeben"]
The login.login becomes a treenode and the "Anmelden" is lost.

**Comment by shanimal** [comment]
Wouldn't this solution force everyone using this module to switch to the new delimiter (`⁂`)? 

Also, how can you have a conflict like `login.login: 'Anmelden',` and `login.login.detail: 'Bitten credentials eingeben'` I've seen this when translations were stored in properties files and converted to a POJO, but I'm having trouble understanding how that conflict could happen in this case, because react-i18nify uses a POJO to store translations.

**Comment by gerbenmeyer** [comment]
This PR could make sence if the KEY_DELIMETER is by default a `.`, but can be changed by e.g. a function like setKeyDelimeter. Till then I'll close this PR.

**Pull request closed without merging**
